"use client";

import React from "react";
import { MessageCircle } from "lucide-react";

interface WhatsAppShareButtonProps {
  diseaseName: string;
  severity: "Low" | "Medium" | "High";
  bioRemedy: string;
  weatherRisk: string;
  location: string;
}

export default function WhatsAppShareButton({
  diseaseName,
  severity,
  bioRemedy,
  weatherRisk,
  location
}: WhatsAppShareButtonProps) {
  
  const generateWhatsAppMessage = () => {
    const text = `🌱 *FloraNet Diagnostic Report*
📍 Location: ${location}

*Detected Issue:* ${diseaseName}
*Severity:* ${severity === 'High' ? '🔴 High' : severity === 'Medium' ? '🟡 Medium' : '🟢 Low'}

*Weather Context:*
${weatherRisk}

*Prescribed Bio-Remedy:*
${bioRemedy}

_Generated by FloraNet Edge Advisory_`;

    return encodeURIComponent(text);
  };

  const handleShare = () => {
    const message = generateWhatsAppMessage();
    window.open(`https://wa.me/?text=${message}`, '_blank');
  };

  return (
    <button
      onClick={handleShare}
      className="flex items-center justify-center gap-2 w-full sm:w-auto px-5 py-3 bg-[#25D366] hover:bg-[#20bd5a] text-white rounded-[12px] font-bold text-[15px] transition-colors shadow-sm"
    >
      <MessageCircle className="w-5 h-5 fill-current" />
      <span>Share Agro-Card to WhatsApp</span>
    </button>
  );
}
