"use client";

import React, { useState } from "react";
import TopBar from "@/components/ui/TopBar";
import FarmProfileInput from "@/components/planner/FarmProfileInput";
import RotationTimeline from "@/components/planner/RotationTimeline";
import SoilHealthGauges from "@/components/planner/SoilHealthGauges";
import MicroclimateAlerts from "@/components/planner/MicroclimateAlerts";
import BioInputSchedule from "@/components/planner/BioInputSchedule";
import CarbonEstimator from "@/components/planner/CarbonEstimator";
import Link from "next/link";
import { Calendar } from "lucide-react";

import SustainabilitySimulator from "@/components/planner/SustainabilitySimulator";
import GeospatialSoilPlanner from "@/components/planner/GeospatialSoilPlanner";
import { getApiBaseUrl } from "@/lib/apiConfig";

export default function PlannerPage() {
  const [loading, setLoading] = useState(false);
  const [planData, setPlanData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  /**
   * Real plan generation: enqueues the backend task
   * (GET /api/v1/satellite/advisory) and polls /api/v1/tasks/{id} for the
   * regenerative plan generated by the local open-source LLM, grounded in
   * live data. No client-side fabricated plan is substituted.
   */
  const handleGeneratePlan = async (soilType: string, crop: string, irrigation: string) => {
    setLoading(true);
    setError(null);
    try {
      // Benchmark coordinates for the demo farm (Pune region)
      const lat = 18.5204;
      const lon = 73.8567;
      const apiBase = getApiBaseUrl();

      const res = await fetch(
        `${apiBase}/api/v1/satellite/advisory?lat=${lat}&lon=${lon}&soil_type=${encodeURIComponent(soilType)}`,
        { signal: AbortSignal.timeout(10000) }
      );
      if (!res.ok) throw new Error(`Backend returned HTTP ${res.status}`);
      const { task_id: taskId } = await res.json();
      if (!taskId) throw new Error("No task id returned");

      // Poll the real Celery task result (plan generation takes ~10-60s)
      const deadline = Date.now() + 120000;
      let result: any = null;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 4000));
        const pollRes = await fetch(`${apiBase}/api/v1/tasks/${encodeURIComponent(taskId)}`, {
          signal: AbortSignal.timeout(8000),
        });
        if (!pollRes.ok) continue;
        const poll = await pollRes.json();
        if (poll.status === "SUCCESS" && poll.result) {
          result = poll.result;
          break;
        }
        if (poll.status === "FAILURE") {
          throw new Error(
            typeof poll.result === "string"
              ? poll.result
              : "Plan generation failed on the backend (check the local Ollama model server / worker logs)"
          );
        }
      }
      if (!result) throw new Error("Plan generation timed out after 2 minutes");

      setPlanData(result);
    } catch (err: any) {
      console.error("Plan generation failed:", err);
      setError(err?.message || "Plan generation failed — no fabricated plan is shown.");
      setPlanData(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <TopBar />

      {/* Navigation Tabs */}
      <div className="flex border-b bg-white overflow-x-auto whitespace-nowrap hide-scrollbar">
        <Link href="/" className="px-4 py-3 text-center text-gray-500 font-medium hover:text-gray-700">
          Diagnose
        </Link>
        <Link href="/planner" className="px-4 py-3 text-center border-b-2 border-green-600 font-semibold text-green-700">
          Rotation Planner
        </Link>
        <Link href="/field-health" className="px-4 py-3 text-center text-gray-500 font-medium hover:text-gray-700">
          Field Intelligence
        </Link>
        <Link href="/analytics" className="px-4 py-3 text-center text-gray-500 font-medium hover:text-gray-700">
          Analytics
        </Link>
        <Link href="/interop" className="px-4 py-3 text-center text-gray-500 font-medium hover:text-gray-700">
          DPG Hub
        </Link>
        <Link href="/seed-network" className="px-4 py-3 text-center text-gray-500 font-medium hover:text-gray-700">
          Seed Network
        </Link>
        <Link href="/seed-finder" className="px-6 py-4 text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors">
          Seed Finder
        </Link>
      </div>

      <main className="p-4 max-w-xl mx-auto space-y-6">
        {/* Live satellite telemetry + Soil Degradation Index + microclimate alerts */}
        <GeospatialSoilPlanner />

        <FarmProfileInput onGenerate={handleGeneratePlan} />
        
        {/* Sustainability "What-If" Preset Delta Sandbox */}
        <SustainabilitySimulator />

        <CarbonEstimator />

        {loading && (
          <div className="flex justify-center items-center mt-10 mb-10">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-green-700"></div>
            <span className="ml-3 text-gray-600">Generating plan from live satellite, soil & weather data…</span>
          </div>
        )}

        {!loading && error && (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 text-center">
            <p className="text-[14px] font-bold text-amber-800">Plan generation unavailable</p>
            <p className="text-[12.5px] text-amber-700 mt-1">{error}</p>
            <p className="text-[11.5px] text-amber-600 mt-2">
              FloraNet does not substitute a fabricated plan when the live pipeline is down.
            </p>
          </div>
        )}

        {!loading && planData && (
          <>
            <SoilHealthGauges 
              assessment={planData.current_soil_health_assessment} 
              degradationIndex={planData.soil_degradation_index} 
            />
            
            <MicroclimateAlerts alerts={planData.microclimate_alerts} />
            
            <RotationTimeline phases={planData.phases} />

            <BioInputSchedule />
          </>
        )}
      </main>
    </div>
  );
}
